### ISSUE TITLE
Provide a sample JWT

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/jsonwebtoken.io#7]
It would be nice to have an example JWT available on the site, so someone can quickly see what it looks like.

**Comment by bretterer** [comment]
Already does.

<img width="1366" alt="screen shot 2017-08-28 at 10 53 37 pm" src="https://user-images.githubusercontent.com/1906920/29806361-bdfac6ea-8c43-11e7-91f0-89bafdae52ef.png">
